/**
 * License - 100% offline activation.
 *
 * No network calls. Ever. The plugin contains a SHA-256 hash list of every
 * valid license key (client/js/keyhashes.js, generated by scripts/generate-keys.js).
 * Activation verifies a user-entered key by hashing it and checking inclusion.
 *
 * After activation, an HMAC-signed token is written to ~/.omni-forge/license.dat.
 * The signature is keyed to the device fingerprint, so copying the file to a
 * different machine invalidates it.
 *
 * The "max 3 devices per key" policy is enforced by your sales process
 * (license terms), not by the plugin - true offline cross-device enforcement
 * is impossible without a server. This is the same model Sketch, JetBrains
 * (pre-2019), and most commercial offline tools used.
 */
(function (global) {
  "use strict";

  // Node integration (CEP exposes it when manifest enables --enable-nodejs)
  function tryRequire(name) { try { return require(name); } catch (e) { return null; } }
  var fs     = (typeof require !== "undefined") ? tryRequire("fs")     : null;
  var os     = (typeof require !== "undefined") ? tryRequire("os")     : null;
  var crypto = (typeof require !== "undefined") ? tryRequire("crypto") : null;
  var path   = (typeof require !== "undefined") ? tryRequire("path")   : null;

  function tokenPath() {
    if (!path || !os) return null;
    var dir = path.join(os.homedir(), ".omni-forge");
    if (fs && !fs.existsSync(dir)) try { fs.mkdirSync(dir, { recursive: true }); } catch (e) {}
    return path.join(dir, "license.dat");
  }

  function fingerprint() {
    if (!os || !crypto) return "unknown-device";
    var parts = [
      os.hostname() || "",
      os.platform() || "",
      os.arch() || "",
      String((os.cpus() && os.cpus()[0] && os.cpus()[0].model) || ""),
      String(os.totalmem() || "")
    ];
    var nics = os.networkInterfaces ? os.networkInterfaces() : {};
    for (var k in nics) {
      var arr = nics[k];
      for (var i = 0; i < arr.length; i++) if (arr[i].mac && arr[i].mac !== "00:00:00:00:00:00") { parts.push(arr[i].mac); break; }
    }
    return crypto.createHash("sha256").update(parts.join("|")).digest("hex");
  }


  function readToken() {
    var p = tokenPath();
    if (!p || !fs || !fs.existsSync(p)) return null;
    try { return JSON.parse(fs.readFileSync(p, "utf8")); } catch (e) { return null; }
  }
  function writeToken(obj) {
    var p = tokenPath();
    if (!p || !fs) return false;
    try { fs.writeFileSync(p, JSON.stringify(obj), "utf8"); return true; } catch (e) { return false; }
  }
  function clearToken() {
    var p = tokenPath();
    if (p && fs && fs.existsSync(p)) try { fs.unlinkSync(p); } catch (e) {}
  }
  function sign(payload, fp) {
    if (!crypto) return "";
    return crypto.createHmac("sha256", fp).update(JSON.stringify(payload)).digest("hex");
  }
  function verifySignature(stored, fp) {
    if (!stored || !stored.payload || !stored.sig) return false;
    return sign(stored.payload, fp) === stored.sig;
  }

  function hashKey(key) {
    if (!crypto) return "";
    return crypto.createHash("sha256").update(String(key).trim().toUpperCase()).digest("hex");
  }
  function isValidKey(key) {
    var list = global.OMNI_KEY_HASHES;
    if (!list || !list.length) return false;
    var h = hashKey(key);
    for (var i = 0; i < list.length; i++) if (list[i] === h) return true;
    return false;
  }


  function activate(key) {
    return new Promise(function (resolve, reject) {
      key = String(key || "").trim().toUpperCase();
      if (!/^OMNI(-[A-Z0-9]{4}){4}$/.test(key)) return reject(new Error("Invalid key format. Expected OMNI-XXXX-XXXX-XXXX-XXXX."));
      if (!fs || !crypto)                       return reject(new Error("Node integration unavailable. Restart After Effects."));
      if (!isValidKey(key))                     return reject(new Error("This license key is not recognized."));

      var fp = fingerprint();
      var payload = {
        key:          key,
        fp:           fp,
        activatedAt:  Date.now(),
        lastCheck:    Date.now()
      };
      var sig = sign(payload, fp);
      writeToken({ payload: payload, sig: sig });
      resolve(payload);
    });
  }

  function validate() {
    return new Promise(function (resolve, reject) {
      var stored = readToken();
      if (!stored) return reject(new Error("No license installed."));
      var fp = fingerprint();
      if (!verifySignature(stored, fp)) {
        clearToken();
        return reject(new Error("License signature invalid (device changed?)."));
      }
      // Re-check the embedded hash list - protects against revoked keys
      // when you ship a plugin update with a refreshed hash list.
      if (!isValidKey(stored.payload.key)) {
        clearToken();
        return reject(new Error("License key no longer recognized. Re-activate with a current key."));
      }
      stored.payload.lastCheck = Date.now();
      stored.sig = sign(stored.payload, fp);
      writeToken(stored);
      resolve(stored.payload);
    });
  }


  function deactivate() {
    return new Promise(function (resolve) {
      clearToken();
      resolve();
    });
  }

  function status() {
    var stored = readToken();
    if (!stored) return null;
    return {
      key:         stored.payload.key,
      activatedAt: stored.payload.activatedAt,
      lastCheck:   stored.payload.lastCheck,
      mode:        "offline"
    };
  }

  global.License = {
    activate:     activate,
    validate:     validate,
    deactivate:   deactivate,
    status:       status,
    fingerprint:  fingerprint,
    isOffline:    true
  };
})(window);
