#!/usr/bin/env node
/**
 * Generate Omni Forge license keys (offline mode).
 *
 * Usage: node scripts/generate-keys.js [count=100]
 *
 * Outputs:
 *   keys/keys.txt              - the keys themselves (distribute to buyers)
 *   client/js/keyhashes.js     - SHA-256 hash list embedded in the plugin
 *                                (the plugin uses this to verify keys offline)
 *
 * SECURITY MODEL
 *   The plugin contains only the HASHES of valid keys, not the keys themselves.
 *   It validates by hashing the user's input and checking inclusion.
 *   Pirates would have to break SHA-256 (impossible) or generate a brand-new
 *   plugin with their own hash list (defeats the point - they'd ship their own
 *   plugin, not yours).
 */
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const COUNT = parseInt(process.argv[2] || "100", 10);
const ROOT = path.join(__dirname, "..");
const KEYS_DIR = path.join(ROOT, "keys");
const HASHES_OUT = path.join(ROOT, "client", "js", "keyhashes.js");

if (!fs.existsSync(KEYS_DIR)) fs.mkdirSync(KEYS_DIR, { recursive: true });

// Avoid ambiguous chars I, O, 0, 1
const ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
function block() {
  const buf = crypto.randomBytes(4);
  let s = "";
  for (let i = 0; i < 4; i++) s += ALPHABET[buf[i] % ALPHABET.length];
  return s;
}
function makeKey() {
  return "OMNI-" + block() + "-" + block() + "-" + block() + "-" + block();
}
function hashKey(k) {
  return crypto.createHash("sha256").update(k.trim().toUpperCase()).digest("hex");
}


const keys = new Set();
while (keys.size < COUNT) keys.add(makeKey());
const list = [...keys];

// 1. The human-readable list you distribute to buyers
fs.writeFileSync(path.join(KEYS_DIR, "keys.txt"), list.join("\n") + "\n");

// 2. The hash list the plugin uses to verify keys offline
const hashes = list.map(hashKey);
const banner = "/* AUTO-GENERATED by scripts/generate-keys.js. Do not edit by hand. */\n";
const body = "window.OMNI_KEY_HASHES = " + JSON.stringify(hashes, null, 2) + ";\n";
fs.writeFileSync(HASHES_OUT, banner + body);

console.log(`Generated ${list.length} keys.`);
console.log(`  ${path.relative(ROOT, path.join(KEYS_DIR, "keys.txt"))}`);
console.log(`     -> distribute these to buyers (one per buyer)`);
console.log(`  ${path.relative(ROOT, HASHES_OUT)}`);
console.log(`     -> embedded in the plugin; rebuild/repack the .zxp after this`);
console.log(`\nFirst 3 keys (for testing):`);
list.slice(0, 3).forEach(k => console.log("  " + k));
